### ISSUE TITLE
Nothing

### ISSUE THREAD

**Issue by DavidBruant** [cascadiajs/2015.cascadiajs.com#161]
Not ready

**Comment by oncletom** [comment]
> Today's search engines use a centralized

_Centralized_ is ambiguous: how centralised can be multiple points of access?

> one-size-fits-all approach that searches the Internet with the same set of tools for all queries.

_same set_ for whom? Because Google aggregates so much in SERP, and specialises results based on the context of the search (enabling you to buy your plane tickets because you look for 2 city names is not what I would call one-size-fits-all).

Maybe you want to convey that you have a unique way to query the Internet: a search input and a flat list of results. Which is nice for _documents_ but not so much to understand how they relate to each other, how genuine and trusted they are. In other other words, you have to trust what is given to you (by commercial entities). Whereas our decisions might not rely only on their private interests.

**Comment by DavidBruant** [comment]
> > Today's search engines use a centralized

> Centralized is ambiguous: how centralised can be multiple points of access?

When you search on Google, Google gives you access to their database. They do not try to give you several angles or approaches. They may help you in filtering (per lang, per city, per time range sort of), but they make the decision of what's important. They don't allow you to say for instance that on Node.js™, you trust Jane and you'd like Jane's favorite websites on the topic to come up first when you search something related to Node.js™ (assuming she agreed to share her expertise with you on this topic).

> same set for whom?

Good point, I'll think about it and come back to it.

> (enabling you to buy your plane tickets because you look for 2 city names is not what I would call one-size-fits-all)

Interesting. Yeah, the topic is specifically document search all services and results that search engines can return when provided a text entry (Google also computes things when given a formula or can answer simple questions like currency exchange rates, but that's beyond the point).
The topic being addressed is "knowledge exploration".
I'll try to narrow down the description.

Thanks @oncletom for the feedback :-)

**Comment by oncletom** [comment]
> They don't allow you to say for instance that on Node.js™, you trust Jane and you'd like Jane's favorite websites on the topic to come up first when you search something related to Node.js™ (assuming she agreed to share her expertise with you on this topic).

That is what their social search is about (and why you could see Google+ avatars of your circle friends amongst the results). I would see the 'Images', 'News', 'Maps' as various angles to query their database. And this is why they are so good, because they link the data altogether (I suppose).
