### ISSUE TITLE
Help Wanted: Significant Others Track

### ISSUE THREAD

**Issue by crtr0** [cascadiajs/2015.cascadiajs.com#17]
CascadiaJS Fest is going to be a destination conference, which means that we will be encouraging people to bring their families up to Semiahmoo for the duration of their stay. The purpose of an SO track is to make sure that SOs (spouses, partners, children, etc) have things to do during the day and enjoy their CJS experience just as much as those who are inside listening to talks. JSConf has been a pioneer here and it's worth [looking at what they did this past year](http://2014.jsconf.us/sotrack.html) as a guide for designing an SO experience for CJS.

*Estimated time commitment:*

- individual hours/wk to accomplish assigned/delegated tasks for event
- meetings along with async check-ins, both increasing in frequency from monthly to bi-monthly to weekly as the conference draws near.
- recommended day before/after as well as the conference event dates

**Comment by GregBulmash** [comment]
Just providing minutes of some brainstorming:

Track organizer does not actually have to be the camp counselor who hands-on supervises all the activities. Part of it is just compiling the list of what's available, what it costs, and keeping people informed. Looking into group discounts/specials.

Polling attendees on whether they're bringing SO's, kids. Developing communication stream with them.

If there are enough kids, kid camps in the evening to allow parents/so's to attend the evening events. Does hotel have staff or there a local company that can provide a kid camp for a fee. Sort of like a day care's Parents Night Out... Cost $35 (or whatever)... Drop kids off at 6 pick kids up at 10. They get pizza dinner and a movie / activities. 

Look into options for a "Club Cascadia" day camp for the kids so an SO can take a spa day. Possibly work with a company out of Bellingham that does kids parties? Maybe hotel has recommendation? What would be the min/max age, ratio of kids to care providers?

**Comment by GregBulmash** [comment]
Summing up from hotel site: Water activities
http://www.semiahmoo.com/water_sports.php
* Whale Watching/Wildlife tours, 12 person boats, private charters for up to 40, leaves 9 a.m. and 1 p.m. for 3-5 hour tours.
* Charter fishing ("bottom fishing, salmon, and crabbing") - same company as whale watching.

Family Stuff - http://www.semiahmoo.com/activities.php
* Kids club - 12:15 - 2:45, $15, limit 6 kids - Offered through the Spa. Can we get them to expand registration with advance notice? Special session for Cascadia Kids?

**Comment by GregBulmash** [comment]
Attraction for parents with kids: Water slides http://www.tripadvisor.com/Attraction_Review-g58359-d1520744-Reviews-Birch_Bay_Waterslides-Blaine_Washington.html

**Comment by RuthieB** [comment]
Hi, Carter! I am considering volunteering for this job, but I am also considering submitting a talk. Is this a horrible idea? 

Also, is the organizer expected to attend all of the SO track activities? My kids will have varying opinions on what they want to do, so I will need to be flexible.

**Comment by GregBulmash** [comment]
Hi Ruthie, At least my first post (minutes of brainstorming) is a record of informal brainstorming with Carter yesterday as he asked me to look into coordinating this since I coordinate Seattle CoderDojo and put on coding events for families most Saturdays. 

How hands-on and how elaborate the track will be is going to depend on the # of people bringing SO's, what the composition of the SO group is (# kids, # adults, general preferences), and what kind of activities are planned. Right now we're expecting a chunk will be curating a good list of DIY activities and maintaining good communication with the attendees, and working with the resort to plan activities that the resort will be in charge of.

**Comment by KatieK2** [comment]
If there is interest, I know someone who could probably be cajoled into organizing some sort of brewery ( the beer kind) tour.

**Comment by KatieK2** [comment]
Random thoughts:

Visitors might want to know whether it's feasible to do a Seattle day trip from the conf venue. And if so, how to travel. 

Ideas for Seattle tourist activities:
 * Seattle Underground Tour
 * Pike Public Market
 * Tacoma Museum of Glass (preferable to the Chihuly, trust me)

**Comment by GregBulmash** [comment]
Semiahmoo Resort to Tacoma Museum of Glass is a 5 hour round trip without
traffic.

**Comment by KatieK2** [comment]
You do save an hour by going to Seattle instead of Tacoma, but you don't get to see any glassblowing in action at Chihuly's Garden. And you only get to see Chihuly's work. Sure, it's nice if you're already going to the Space Needle.

But if you want to see glass by a multiple artists, and watch glassblowers work live, my advice is Tacoma MoG.

If you want to take a glassblowing lesson, I know some people. ;)

**Comment by GregBulmash** [comment]
I'm sorry, but do we really want to recommend a "day trip" that involves
8-9 hours on the road? Remember that the S.O. track is happening at the
same time as the con, so Tacoma MoG is not only almost 300 miles, but in
weekday traffic.

Vancouver is WAY closer.

**Comment by KatieK2** [comment]
I was just saying that folks might want to know *whether* a trip to Seattle was feasible. If Vancouver CA is better, that's cool - they'll just want to know. ;)

(I have strong opinions on the Seattle glassblowing thing because it's one of my hobbies.)

**Comment by hackygolucky** [comment]
We may not have to resort to a daytrip that's far at all. We might want to
explore adventures that are close to the gorgeous venue we've selected, as
it seems like there's a ton without needing to venture on a long drive.

**Comment by GregBulmash** [comment]
I've been exploring options around Semiahmoo and Bellingham. When we've got
the contract signed and can more easily tap the resort's resources, a
coordinator can get some time with their staff and get a brain dump on the
stuff that's not in Yelp, as well as custom options the resort can offer.

The main time area of this is going to be making sure we're collecting data
on attendees/speakers who are bringing S.O.s (how many adults, how many
kids, age ranges), then work with the resort to plan accordingly and
provide a curated list of additional suggestions.

Personally, if I brought my wife and kids, I'd feel distracted during the
day and drawn away from the evening events to be with them. That's why I
don't want to bring them. I want to get my investment's worth from
attending by making the most of the conference and all the networking
opportunities.

Are we shooting ourselves in the foot by encouraging S.O. attendance? Do we
end up encouraging con attendees to bring distractions with them that will
make it harder to get the full value the event offers?

**Comment by brycebaril** [comment]
I've taken my family to a few conferences now, it is *not* a distraction. They are part of the community, and especially the kids really get a lot out of seeing what tech conferences are like and feeling included. I find missing them more distracting than having them around.

The best way to do the SO track appears to be SO track as an optional alternative to attending the talks, then the other (e.g. evening) events *include* the families.

As for how far afield to travel, I would suggest on-site or walking distance. Taking everyone to Vancouver, Tacoma, or Seattle is coordination and travel stress and lots of time.

**Comment by GregBulmash** [comment]
Bryce,

This is a resort in the boonies. It has a pool, golf courses, spa, hiking...

There's not really much within walking distance. Unlike prior CascadiaJS
events, this isn't smack dab in the middle of a vibrant city. It's a
getaway destination.

The closest cities with a big enough population to support a decent
shopping/activity district are Bellingham and Vancouver. Barring a HUGE
S.O. contingent that warrants arranging bus tours, anything offsite will
probably be BYO transportation / carpool coordination.

That said, I'd love to hear how you've involved your kids in conferences
before and what more you believe could be done in the evenings:
   Family hours (between 6-8) with an adults-only afterparty?
   "Parents Night Out" where we get one of the conference rooms set up with
pillows, pizza, a few adult supervisors and a movie? Drop kids off at 6,
pick them up by 10?

One of the reasons Carter asked me to be on the S.O. track thread is
because I run Seattle CoderDojo, a volunteer group that runs a free
Saturday Morning coding club for kids. We regularly host 80-90 kids on a
Saturday morning and our Hour of Code event had 185 kids.

I'm willing to run some coding camp activities for kids on CSS day, but
I'll need volunteers.

- Greg

**Comment by hackygolucky** [comment]
Carter has enlisted the help of Megan Christian, an amazing event planner,
and along with the Semiahoo staff we'll probably be able to get some really
quality info on what is reasonable to provide. The SO track is pretty
important(even if it's casual) for this time of the year. There will
certainly be a group of people not wanting to bring their family, and
others who can't swing the trip if there isn't something in it for the fam
too.

JSConf and NodeConf are two great examples of 'destination' conferences
that are doing a fun job of making the SO track workable. These confs can
be a priority for some developers explicitly because they offer this. We've
tried to make the conference open to all types of developers but have
frustrated ourselves in past years to not giving enough space for an SO
track or daycare of any sort. We hope to put more energy into it now.

Events include arts and crafts, coding time aimed at non-coders and kids,
adventure time without the coders, etc.

The SO track doesn't have to go off-campus at all. It's all up to the
person organizing the track to get creative with the constraints provided
and expand the ideas if it's reasonable to do so. Greg, happy to get on a
call with you and Carter so that we're on the same page and you're not
feeling overwhelmed. It certainly won't be done alone!

**Comment by hackygolucky** [comment]
Also, thanks for your input Bryce! I know you and Ruth have had a blast at
some conferences thanks to an SO track. I'm excited to make room for this
in Cascadia and knowing attendees that have good insight and willing to
share makes it able for us to offer it, make it fun.

**Comment by RuthieB** [comment]
Bryce and I are happy to help, Tracy! I admit, our vision for an SO track matches what we have experienced at Nodeconf, which is very inclusive of the family. The purpose of the SO track there is to have fun (and maybe learn something) while the attendees are at the talks/sessions, and the families are just part of the gang the rest of the time! 

I know that Carter has talked to Mikeal about the overwhelmingly positive response he gets from the families (and the singletons!) who attend this conference-- those who brought their kids vow to return every year, and those that did not bring their kids wish they had. Our 12-year-old was so deeply impacted by what she learned last year at Nodeconf that she is doing her 6th grade "Passion Project" on the experience. 

The activities you mentioned-- crafts, exploration of the immediate area, and coding-- were more than enough to keep our three kids occupied and very happy for the three full days of the conference. Also, don't forget the fact that the kids will likely make friends with each other and provide their own sort of fun! I found myself wishing I had registered as an attendee because I had so much more free time than expected. We have been to Semiahmoo, and I trust we will have no problem finding ample opportunities for fun and education on-site.

**Comment by KatieK2** [comment]
Here is a piece of prior art that may come in handy. 

SassConf was held in New York City and they expected a lot of out-of-town visitors and that folks would combine a vacation with a trip for the conference. They put together this lovely visitor's guide: http://web.archive.org/web/20131123003251/http://sassconf.com/pages/nyc-primer/

**Comment by hackygolucky** [comment]
Suggestion from @jasonrhodes at brooklyn.js http://www.birchbaywaterslides.net/

**Comment by stacfabs** [comment]
Hello all. I've not been to a tech conference as a significant other before and only attended as a local so I might be missing some assumptions, but in reading this above thread I had a couple thoughts and questions.

* Kids under 4 generally are going to be happy with just a bunch of toys and play friends.
* Will age groups be separated for interest? 
* What about children of the nap age? Half day option?
* Is there cost per child or just included with SO track?
* Not all SOs are women so a "spa day" is not the only thing to offer. 
* Will snacks and lunch be provided by the organization or does the parent need to provide that?

I might be getting ahead of the logistics you're thinking of right now, but as a mother of a 3.5 and 2 yr old, these are the thing that pop into my mind from the perspective of it I was the SO going with my kids in tow.

Thanks!

**Comment by TheAlphaNerd** [comment]
@mikeal do you have any thoughts or anything you could add?

**Comment by davethegr8** [comment]
Hi @stacfabs! We're still very early in the planning process for the SO track. I'm not sure that we have anything confirmed at this point, but we'll take your questions into account as we're putting it together. If you have anything in particular that you'd like to see (besides what you mentioned already) please let us know!

**Comment by hackygolucky** [comment]
For reference, @stacfabs wrote this great post
http://zomigi.com/blog/we-need-more-moms-in-web-design-and-development/ and
I thought it had some really great insight and perspective. Thanks for
stepping into this planning and giving us questions we need to ask as we
move forward!

**Comment by stacfabs** [comment]
@hackygolucky , your words are very kind. I wish I could take credit for that well written and very poingent post, but it was actually by Zoe Mickley Gillenwater (http://zomigi.com/about/ @zomigi on Twitter). I do, however, very much agree with her point of view. I also have an event planning background and very current point of view on mothers in coding as I just finished the Full-Stack JavaScript Course at Portland Code School and now work as a Developer at WebMD Health Services, both here in Portland, OR. I will happily contribute/help in any way I can.

**Comment by KatieK2** [comment]
Hi @RuthieB @brycebaril @stacfabs Are any or all of you still excited about (and able to) lead the SO Track ?

**Comment by RuthieB** [comment]
Hi @KatieK2 !! @brycebaril and I are so disappointed to be missing Cascadia this year (this will be Bryce's first year to miss it), because we will be visiting family that week. If you need any general advice/suggestions/opinions, we will be happy to help. :)

**Comment by crtr0** [comment]
Thanks to Michael and Megan Saffitz for volunteering to lead the SO Track!

**Comment by ivanoats** [comment]
@KatieK2 thanks for chatting with me about SO track tonight at SeattleJS - happy to help

**Comment by KatieK2** [comment]
Hi @ivanoats - it was good chatting with you! Let me introduce you to @GregBulmash who I think is running a kids+code event at Cascadia Fest. Greg - Ivan has volunteered to help with your workshop in case you need any extra hands!
