### ISSUE TITLE
Build desktop applications with NW.js

### ISSUE THREAD

**Issue by asalkey** [cascadiajs/2015.cascadiajs.com#250]
# Build desktop applications with NW.js

* Name      : Andrea Salkey
* Location  : Seattle, WA
* Email     : andreasalkey@gmail.com
* Twitter   : [@asalkey_](https://twitter.com/asalkey_)
* GitHub   : [asalkey](https://github.com/asalkey)
* Url(s)     : [www.salkey.com](http://www.salkey.com)

## The story you'd like to tell
You can build desktop applications with HTML,CSS and JavaScript! No, I am not talking about widgets. I mean actual applications you can install on your Linux, OSX, or Windows machine.

In this talk I will discuss:

1. What is NW.js - an overview on the architecture and history behind it.
2. How to get up and running - an overview on how to setup NW.js and the structure of a basic app 
3. Packaging - an overview on how to package your app for distribution on a Linux, OSX, or Windows machine.
4. Demo time! - a demo of an application I made
5. Tips and tricks - what I learned from building an app

After this talk the audience will have a better understanding as to what NW.js is and how to use it to build desktop applications.

## Speaker Bio
![](https://cloud.githubusercontent.com/assets/1271601/6590351/8e0e8786-c76b-11e4-80a4-f3f8a2e9a545.png)

Andrea is a self-taught full-stack developer. She enjoys cheese and naps.

**Comment by KatieK2** [comment]
Hi Andrea, I'm part of the Browser JS talk review committee. This is an interesting proposal - thank you for submitting it! It would be helpful to understand a little more detail about this presentation, and also what takeaways the attendees might take away from it.
I do recommend that you update the main proposal body (the issue) because it's the only thing that - when we're reading and evaluating all 200 talks - every person is guaranteed to see. Thanks!

**Comment by asalkey** [comment]
@KatieK2 done!
