### ISSUE TITLE
Talk: Asynchronous js without promises

### ISSUE THREAD

**Issue by jtrinklein** [cascadiajs/2015.cascadiajs.com#4]
I would like to see a talk about async programming in js without using promises

**Comment by bsiddiqui** [comment]
:+1:

**Comment by davethegr8** [comment]
Dibs. Created talk proposal #76.

If anyone else wants it though, I'm happy to let someone else have it.

**Comment by baer** [comment]
I should have submitted #80 this last night instead of re-writing it 100 times :).
*Furiously re-reading Lean Startup*

I DO want to talk about Promises but I don't want to focus on a specific technology I want to talk patterns so I'm not sure if this talk fits or not. @davethegr8 Wanna :moyai: :page_facing_up: :scissors: for it?

**Comment by davethegr8** [comment]
I throw :bomb:! I win!

Kidding. :)

What I was planning to talk about was when different systems are useful, since they all have a place. I was going to address callbacks and (dom) events as different systems, since while they are similar there are different practical applications. Then there's also event emitters which have subtly different applications. I wanted to introduce a somewhat novel idea of state machines for async control since they have been helpful to me in my work, and I could see them helping others also. Moreover, my focus was going to be on what we can do *today* rather than tomorrow/someday.

Looking at your proposal, I hadn't considered web workers as part of this, and while I'm not sure what place they could hold, I'm curious to see what you'd use them for. I have yet to see a useful example of generators besides "look I can calculate Fibonacci numbers" so I'd also love to hear how that would be practical. 

So, given all that, do you think that our proposals are different enough? Is there overlap, or are we approaching the problem from different directions, with different solutions?

But bottom line, I'd prefer you getting your talk over me getting it, so if you want it I'll close mine.

**Comment by thure** [comment]
With #74 I'd like to focus on state machines / statecharts, so 'async-without-promises' could potentially become a series of talks. I'd be down to collaborate.

**Comment by davethegr8** [comment]
Oh cool, I didn't quite grok that from the proposal. :) I'll close my proposal.

**Comment by baer** [comment]
@davethegr8 - Thanks for the great response I'd love to get to chat at Cascadia about some of that stuff - especially where you're using state machines for async. I'm pretty sure that Promises are built with state machines btw. I'll be implementing a mini Promise lib to do some research and I'll find out more on that.

@thure - Since @davethegr8 closed his that leaves the two of us so far with this async stuff. I wasn't really going to do much with state machines but we should definitely collaborate a bit so we don't overlap too much.

**Comment by baer** [comment]
@jtrinklein - What's wrong with Promises anyway? I quite like them.
