### ISSUE TITLE
Help Wanted: Curators

### ISSUE THREAD

**Issue by crtr0** [cascadiajs/2015.cascadiajs.com#6]
Please leave a comment if you are interested in being Curator for one of the days below. Please include links to events that you have organized in the past. 

A Curator is considered a core-organizer for CascadiaJS. The Curator will have the ability to delegate as one sees fit, but will be provided extensive guidance/support/tooling on what we've seen work in the past, and what the accountabilities are. Curators should understand that anything that isn't getting done on the timeline laid out(that's been delegated) is something they'll have to do themselves(this will happen, guaranteed). Responsibilities include the cohesion of the talks/events occuring during the event, managing the components that lead up to the event(speaker selection, volunteer coordination, sponsors, vendors, coordinating with other core-organizers).

Estimated time commitment:
- individual hours/wk to accomplish assigned/delegated tasks for event
- meetings along with async check-ins, both increasing in frequency from monthly to bi-monthly to weekly as the conference draws near.
- recommended day before/after as well as the conference event dates 
  
  
**Event of interest:**
- [x] CascadiaJS Fest overarching coordination(Carter Rabasa & Tracy Hinds)
  - [x] CSS Day
  - [x] Browser Day
  - [x] Node Day

**Comment by thefoxis** [comment]
Here are my two cents with regards to curators&mdash;at [JSFest Oakland](http://oakland.jsfest.com/) each event had one curator (I think with the only exception of HapiDay organised by both Eran and Ben) that was responsible for choosing speakers, setting up a website and overall event promotion (if they wanted to), figuring out the schedule for the day and leading the conference (with the help of MCs if they wanted to as well).

Taking away the the somewhat mundane work of finding sponsors and figuring out the logistics was surely very empowering and led to, in my opinion, great, diverse lineups and very high level of presentations. I think it's important for the curators to take both responsibility and ownership of their events. If it's necessary it can be two people but I think it worked pretty well with one. If it's basically a stand-alone event that has to be organized from ground up you might even need 2-3 core organisers per event for the purpose of speaker selection, scheduling and high level goals and some volunteers for helping out speakers, registration, etc (it varies across CSSConfs but it's good to have help and be clear about delegating tasks, like @crtr0 is already successfully doing).

I wouldn't say it's necessary for the curator(s) to be a well-known person in the industry but I certainly noticed that it helps with promotion, getting the word out, getting diverse lineup of speakers and whatnot. Basically the more exposure that person has, the better. I actively reached out and invited women to apply to speak and also asked well-known designers and developers to tweet/retweet to get even more exposure, so you can "hack" those things.

In general, I'd say&mdash;people who are already doing community work and are somewhat known in the given field are your best bet, but that doesn't mean anyone who doesn't fit that "criteria" would be a bad fit, but they might need more guideance so a good idea might be to pair more seasoned curators with someone who's eager to get involved. Putting a conference is actually quite a lot of work (even minus organisational tasks I've mentioned above) so those people need to be aware what they're in for (usually it's done because of passion anyway so they're prepared to handle whatever amount of time it needs).

It could be a good option to get someone who's local to Oregon or Washington to make things easier and build stronger community bonds but I've successfully organised CSSConf Oakland from my home in Poland so I wouldn't say it's a necessity at all.

I hope that clarifies/helps a bit, I'm happy to suggest people, advise or help out!

**Comment by hackygolucky** [comment]
This is awesome insight, @thefoxis! 

To update everyone, today I'll be delivering a detailed draft of the entire conference planning calendar from scheming in January to full-fledged delivery in July. @crtr0 and I hope to be talking with those who have expressed interest in curating shortly and reaching out to some people who may not have seen these Issues but would be awesome.  Sometimes people need encouragement!

And we need to get the ball rolling :D

Conversations surrounding the time commitment and tasks involved for those who expressed interest should help manage expectations of these roles. This should help us form the core team for the overall conference-- @crtr0, the curators for each day, and myself. This may be delineated from the team for each day and is managed/chosen by the Curator.

Stay tuned and please continue to share anyone you'd think would be a wonderful addition to CJS 2015!

**Comment by nvcexploder** [comment]
I am down to help also - @brycebaril, @othiym23, and @ryan-roemer: if I may be of service for the node specific day, please let me know.

**Comment by othiym23** [comment]
@crtr0 Hey, what's going on with this? Neither @brycebaril nor I ever heard anything about what you decided to do about curating the Node day, and we're both still interested in helping!
