### ISSUE TITLE
Help Wanted: Website

### ISSUE THREAD

**Issue by crtr0** [cascadiajs/2015.cascadiajs.com#7]
Own the web content cradle to grave, including updates as tickets go on sale, speakers are announced, etc. Please leave a comment if you're interested in this role and leave links to website that you've produced that you're proud of.

This responsibility tends to be very front-loaded in the timeline of planning the conference. Assistance with items such as the copy for events and speakers will be provided by organizers responsible for these concerns but will be coordinated by you.

- [ ] Cascadia JSFest(entire conference that encompasses components below)
  - [ ] CSS Day
  - [ ] Browser Day
  - [ ] Node Day

**Estimated time commitment:**
- individual hours/wk to accomplish assigned/delegated tasks for event
- meetings along with async check-ins, both increasing in frequency from monthly to bi-monthly to weekly as the conference draws near.
- recommended day before/after as well as the conference event dates

**Comment by zachattack** [comment]
Hello. I would be happy to help out with design and development also. I am a frontend dev/designer, currently at SXSW, and have worked/volunteerd time on community based events such as Drupal Camp Austin [http://2011.drupalcampaustin.org/](http://2011.drupalcampaustin.org/) for which I did all the design and most of the implementation. I could certainly own chunks of the cradle to grave, the only real issue is that during March I am mostly unavailable.

You can see some more of my work online at:

 * [sxsw.com](http://sxsw.com)
 * [shedaustin.com](http://shedaustin.com)

**Comment by AdityaManohar** [comment]
I'd be happy to help build/maintain/fix the website/application. I like automation and can help with writing some of the automation to keep things running smoothly leading up to the conference and after (audits etc.).

**Comment by hackygolucky** [comment]
Woohoo! Closing this out.

 Please welcome @davethegr8 as our Website Coordinator for CJSFest 2015! He'll be reaching out to those of you who volunteered to help as we move forward with building the website. Thanks y'all.
