### ISSUE TITLE
Talk: CSS regression testing with Scout

### ISSUE THREAD

**Issue by mennovanslooten** [cascadiajs/2015.cascadiajs.com#72]
# Title of Talk

* Name      : Menno van Slooten
* Location  : Amsterdam, The Netherlands
* Email     : menno.vanslooten@gmail.com
* Twitter   : [@mennovanslooten](https://twitter.com/mennovanslooten)
* GitHub    : [mennovanslooten](https://github.com/mennovanslooten)
* Url(s)    : [mennovanslooten.nl](http://mennovanslooten.nl)

## CSS regression testing with Scout

The only way to truly test CSS is in its natural habitat: a browser. Unfortunately, you need to add HTML, some JavaScript and a healthy dose of user interaction to really explore all the effects of new rules and
    changes. Manual testing gets tedious and is error-prone, but automated functional testing always required an unreasonable amount of complex programming...until now.

Scout is a brand new functional testing tool aimed at developers of all levels that makes simulating user behavior and auditing the results a breeze. In this talk I will live code a complete set of tests for an existing project and show how Scout can save the day by catching visual and functional regressions in a number of common scenarios.

## Speaker Bio

![](https://avatars0.githubusercontent.com/u/252087)

Menno is a front-end developer from Amsterdam and likes making people happy. He is totally the lead guitarist in a band.

Previous speaking experience: http://lanyrd.com/profile/mennovanslooten/sessions/

**Comment by alexlande** [comment]
Hi @mennovanslooten, thanks for submitting this talk! I have a few suggestions for your proposal that might help in the review process.

- You may want to emphasize the distinction between Scout and other CSS regression testing tools, namely that Scout is much more of a functional testing environment than other tools which simply open a webpage and take screenshots. Scout's user behavior-simulating features aren't immediately clear.
- There's nothing wrong with providing a demo and overview of an application that you've built (Scout, in this case), but it might make your proposal more compelling to build more of a narrative into it, rather than only demonstrating Scout's feature-set.

**Comment by mennovanslooten** [comment]
Hey @alexlande, thanks so much for your input. I've modified the original proposal.

**Comment by alexlande** [comment]
@mennovanslooten Awesome, looks great!
